"""tablones

Revision ID: 5e8c8415bfa0
Revises: f229a645886b
Create Date: 2026-02-24 22:36:08.139244

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5e8c8415bfa0"
down_revision = "f229a645886b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
