"""add_meetup_fields

Revision ID: b8f2dc47f913
Revises: 5e8c8415bfa0
Create Date: 2026-02-25 21:32:54.310382

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b8f2dc47f913"
down_revision = "5e8c8415bfa0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("meetups", sa.Column("city", sa.String(length=100), nullable=True))
    op.add_column("meetups", sa.Column("pinCode", sa.String(length=20), nullable=True))
    op.add_column("meetups", sa.Column("date", sa.DateTime(timezone=True), nullable=True))
    op.add_column("meetups", sa.Column("startTime", sa.String(length=20), nullable=True))
    op.add_column("meetups", sa.Column("endTime", sa.String(length=20), nullable=True))
    op.add_column("meetups", sa.Column("types", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("meetups", "types")
    op.drop_column("meetups", "endTime")
    op.drop_column("meetups", "startTime")
    op.drop_column("meetups", "date")
    op.drop_column("meetups", "pinCode")
    op.drop_column("meetups", "city")
    # ### end Alembic commands ###
