"""tablones

Revision ID: f229a645886b
Revises:
Create Date: 2026-02-24 17:58:00.223196

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision = "f229a645886b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "google_pois",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("place_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("main_category", sa.String(length=100), nullable=True),
        sa.Column("raw_categories", sa.Text(), nullable=True),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, dimension=2, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("place_id"),
    )
    op.create_table(
        "meetups",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "osm_pois",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("osm_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("cuisine", sa.String(length=255), nullable=True),
        sa.Column("address", sa.Text(), nullable=True),
        sa.Column("main_category", sa.String(length=100), nullable=True),
        sa.Column("raw_tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT", srid=4326, dimension=2, from_text="ST_GeomFromEWKT", name="geometry"
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_osm_pois_osm_id"), "osm_pois", ["osm_id"], unique=True)
    op.create_table(
        "meetup_participants",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("meetup_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="POINT",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.Column("travel_mode", sa.String(length=20), nullable=False),
        sa.Column("max_minutes", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["meetup_id"], ["meetups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meetup_participants_meetup_id"), "meetup_participants", ["meetup_id"], unique=False)
    op.create_table(
        "poi_mapping",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("google_poi_id", sa.Integer(), nullable=False),
        sa.Column("osm_poi_id", sa.Integer(), nullable=False),
        sa.Column("distance_meters", sa.Float(), nullable=True),
        sa.Column("similarity_score", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(["google_poi_id"], ["google_pois.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["osm_poi_id"], ["osm_pois.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("google_poi_id", "osm_poi_id"),
    )
    op.create_index(op.f("ix_poi_mapping_google_poi_id"), "poi_mapping", ["google_poi_id"], unique=False)
    op.create_index(op.f("ix_poi_mapping_osm_poi_id"), "poi_mapping", ["osm_poi_id"], unique=False)
    op.create_table(
        "meetup_isochrones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                dimension=2,
                from_text="ST_GeomFromEWKT",
                name="geometry",
                nullable=False,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["participant_id"], ["meetup_participants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_meetup_isochrones_participant_id"), "meetup_isochrones", ["participant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_meetup_isochrones_participant_id"), table_name="meetup_isochrones")
    op.drop_table("meetup_isochrones")
    op.drop_index(op.f("ix_poi_mapping_osm_poi_id"), table_name="poi_mapping")
    op.drop_index(op.f("ix_poi_mapping_google_poi_id"), table_name="poi_mapping")
    op.drop_table("poi_mapping")
    op.drop_index(op.f("ix_meetup_participants_meetup_id"), table_name="meetup_participants")
    op.drop_table("meetup_participants")
    op.drop_index(op.f("ix_osm_pois_osm_id"), table_name="osm_pois")
    op.drop_table("osm_pois")
    op.drop_table("meetups")
    op.drop_table("google_pois")
    # ### end Alembic commands ###
